#!/usr/bin/env node
/**
 * install-hooks.mjs — 安装 git pre-commit hook
 *
 * 行为：在 .git/hooks/pre-commit 写入一个 shell 脚本，pre-commit 时跑：
 *   1. npm run inventory:check
 *   2. npm run verify -- --scope=nomod --warn-only       (生成 session 提示用)
 *
 * 设计：
 *   - 不强依赖 husky / lefthook，纯 git hook 一行 install。
 *   - inventory:check 是硬拦（drift 必须先 sync）；nomod 默认 warn-only 防止误伤
 *     正常 modify session；当你确定在做 generate 时手动跑 `npm run verify -- --scope=nomod` 才是硬检查。
 *
 * 用法：
 *   npm run hooks:install            # 一次性
 *   npm run hooks:install -- --force # 覆盖现有 hook
 *   npm run hooks:uninstall          # 删除
 */

import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile, chmod, unlink } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const hookDir = join(root, '.git', 'hooks')
const hookFile = join(hookDir, 'pre-commit')

const args = process.argv.slice(2)
const uninstall = args.includes('--uninstall')
const force = args.includes('--force')

const HOOK_MARK = '# cowork-tv-demo pre-commit hook v1'
const HOOK_BODY = `#!/bin/sh
${HOOK_MARK}
# Generated by scripts/install-hooks.mjs — re-run npm run hooks:install to update.

set -e

# 1. inventory drift — hard fail
NODE_ENV=development node scripts/inventory-check.mjs

# 2. no-mod check — soft warn (不硬拦，避免误伤正常 modify session)
#    生成阶段提交前请手动跑：  npm run verify -- --scope=nomod
NODE_ENV=development node scripts/no-mod-check.mjs --warn-only || true
`

if (uninstall) {
  if (existsSync(hookFile)) {
    const text = await readFile(hookFile, 'utf8')
    if (text.includes(HOOK_MARK)) {
      await unlink(hookFile)
      console.log(`✓ removed ${hookFile.slice(root.length + 1)}`)
    } else {
      console.log(`! ${hookFile.slice(root.length + 1)} exists but was not installed by us; leaving alone.`)
    }
  } else {
    console.log('no hook to remove')
  }
  process.exit(0)
}

if (!existsSync(join(root, '.git'))) {
  console.error('error: no .git/ directory found. Are you running this from the repo root?')
  process.exit(2)
}

await mkdir(hookDir, { recursive: true })

if (existsSync(hookFile) && !force) {
  const existing = await readFile(hookFile, 'utf8')
  if (existing.includes(HOOK_MARK)) {
    console.log('✓ hook already installed (up to date or older version); re-installing')
  } else {
    console.error(`error: ${hookFile.slice(root.length + 1)} exists and was not installed by us.`)
    console.error('       use --force to overwrite, or merge manually.')
    process.exit(1)
  }
}

await writeFile(hookFile, HOOK_BODY)
await chmod(hookFile, 0o755)
console.log(`✓ installed ${hookFile.slice(root.length + 1)}`)
console.log('  runs on every git commit:')
console.log('  - inventory:check     (hard fail)')
console.log('  - no-mod-check --warn-only')
console.log('')
console.log('  to remove: npm run hooks:uninstall')
